sudo: required
dist: trusty

env:
  - BAZEL=0.7.0
  - ANDROID_SDK=3859397

before_install:
  - sudo apt-get update -qq
  # Bazel dependencies:
  - sudo apt-get install -qq pkg-config zip g++ zlib1g-dev unzip
  # Project dependencies:
  - sudo apt-get install -qq python-pyicu
  # Install Bazel:
  - wget https://github.com/bazelbuild/bazel/releases/download/${BAZEL}/bazel-${BAZEL}-installer-linux-x86_64.sh
  - sha256sum -c third_party/bazel-${BAZEL}-installer-linux-x86_64.sh.sha256
  - bash bazel-${BAZEL}-installer-linux-x86_64.sh --user
  # Install Android SDK:
  - wget https://dl.google.com/android/repository/sdk-tools-linux-${ANDROID_SDK}.zip
  - sha256sum -c third_party/sdk-tools-linux-${ANDROID_SDK}.zip.sha256
  - sudo mkdir -p -m 1777 /usr/local/android-sdk
  - unzip sdk-tools-linux-${ANDROID_SDK}.zip -d /usr/local/android-sdk
  - echo y | /usr/local/android-sdk/tools/bin/sdkmanager 'build-tools;26.0.3' 'platforms;android-24'

script:
  - bazel test --nodistinct_host_configuration //...
