sudo: required
dist: trusty
language: python

branches:
  except:
    - docker-integration
    - docker-test

env:
  global:
    - ANDROID_SDK=4333796
    - JAVA_OPTS='-XX:+IgnoreUnrecognizedVMOptions --add-modules java.se.ee'

matrix:
  fast_finish: true
  include:
    - os: linux
      python: 2.7
    - os: linux
      python: 3.3
    - os: linux
      python: 3.7-dev
    - os: osx
      language: cpp
      env: PY=/usr/bin/python2.7
  allow_failures:
    - os: osx
      language: cpp
      env: PY=/usr/bin/python2.7

before_install:
  - . travis/before_install.sh

install:
  - yes | "$ANDROID_HOME/tools/bin/sdkmanager" 'build-tools;28.0.2' 'platforms;android-28' > /dev/null
  - pip install -r travis/requirements.txt

script:
  - travis/script.sh
