sudo: required
dist: trusty
group: travis_latest
language: python

python:
  - "2.7"
  - "3.3"

env:
  global:
    - ANDROID_SDK=3859397
  matrix:
    - BAZEL=0.4.5
    - BAZEL=0.5.4
    - BAZEL=0.8.1

matrix:
  exclude:
    - python: "3.3"
      env: BAZEL=0.4.5

before_install:
  # Install ICU (backported to Trusty; fix this when Xenial becomes available):
  - sudo add-apt-repository ppa:suawekk/trusty-backports -y
  - sudo apt-get update -q
  - sudo apt-get install libicu-dev -y
  - icuinfo || /bin/true
  # Install Android SDK:
  - wget https://dl.google.com/android/repository/sdk-tools-linux-${ANDROID_SDK}.zip
  - sha256sum -c third_party/sdk-tools-linux-${ANDROID_SDK}.zip.sha256
  - sudo mkdir -p -m 1777 /usr/local/android-sdk
  - unzip sdk-tools-linux-${ANDROID_SDK}.zip -d /usr/local/android-sdk
  - echo y | /usr/local/android-sdk/tools/bin/sdkmanager 'build-tools;26.0.3' 'platforms;android-24'

install:
  # Install Bazel:
  - wget https://github.com/bazelbuild/bazel/releases/download/${BAZEL}/bazel-${BAZEL}-installer-linux-x86_64.sh
  - sha256sum -c third_party/bazel-${BAZEL}-installer-linux-x86_64.sh.sha256
  - bash bazel-${BAZEL}-installer-linux-x86_64.sh --user
  # Install necessary additional Python modules:
  - pip install -r travis/requirements.txt

script:
  - travis/script.sh
