sudo: required
dist: trusty
language: python

branches:
  except:
    - docker-integration
    - docker-test

env:
  global:
    - ANDROID_SDK=3859397

matrix:
  include:
    - os: linux
      python: 2.7
    - os: linux
      python: 3.3
    - os: linux
      python: nightly
    - os: osx
      env: PY=/usr/bin/python2.7
    - os: osx
      env: PY=python3
  allow_failures:
    - os: linux
      python: nightly
    - os: osx
      env: PY=/usr/bin/python2.7
    - os: osx
      env: PY=python3

before_install:
  - . travis/before_install.sh

install:
  - yes | "$ANDROID_HOME/tools/bin/sdkmanager" 'build-tools;26.0.3' 'platforms;android-24'
  - pip --version
  - pip install -r travis/requirements.txt

script:
  - travis/script.sh
