sudo: required
dist: trusty
language: python

python:
  - "2.7"
  - "3.3"

matrix:
  exclude:
    - python: "3.3"
service:
  - docker

before_install:
  - cd docker-images/test-merlin
  - docker build -t test-merlin .

install:
  - echo `pwd`

script:
  - bash setup_test.sh
